# Generated by Django 5.0.4 on 2024-04-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnnotationSite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selection',
            name='image_data',
        ),
        migrations.AddField(
            model_name='selection',
            name='image',
            field=models.ImageField(default=None, upload_to='selections/'),
            preserve_default=False,
        ),
    ]
